######################################################################
# Automatically generated by qmake (3.0) ?? 12? 7 21:40:01 2016
######################################################################
QT += widgets
TEMPLATE = app
TARGET = quit
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
