######################################################################
# Automatically generated by qmake (3.0) ?? 12? 7 22:03:29 2016
######################################################################
QT += widgets
TEMPLATE = app
TARGET = signal
INCLUDEPATH += .

# Input
SOURCES += signal.cpp
