######################################################################
# Automatically generated by qmake (3.0) ?? 12? 7 21:26:09 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
