######################################################################
# Automatically generated by qmake (3.0) ?? 12? 10 15:51:35 2016
######################################################################
QT          += widgets
TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
