######################################################################
# Automatically generated by qmake (3.0) ?? 12? 9 00:19:47 2016
######################################################################

QT      += widgets

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
