######################################################################
# Automatically generated by qmake (3.0) ?? 12? 11 14:03:08 2016
######################################################################

QT      += widgets

CONFIG  += uitools

TEMPLATE = app
TARGET = dynamicDialog
INCLUDEPATH += .

# Input
FORMS += sortdialog.ui
SOURCES += main.cpp
