######################################################################
# Automatically generated by qmake (3.0) ?? 12? 9 00:14:51 2016
######################################################################
QT      += widgets
TEMPLATE = app
TARGET = find
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
