######################################################################
# Automatically generated by qmake (3.0) ?? 12? 10 22:09:25 2016
######################################################################
QT      += widgets
TEMPLATE = app
TARGET = sort
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    sortdialog.cpp

FORMS += \
    sortdialog.ui

HEADERS += \
    sortdialog.h
