######################################################################
# Automatically generated by qmake (3.0) ?? 12? 11 00:24:19 2016
######################################################################
QT      += widgets
TEMPLATE = app
TARGET = tabDialog
INCLUDEPATH += .

# Input
SOURCES += main.cpp

FORMS +=
